version: '3.1'

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 112a

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 112a
      ME_CONFIG_MONGODB_URL: mongodb://root:112a@mongo:27017/
    depends_on:
      - mongo

  postgres:
    image: "postgres:14.5-alpine"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=noteflow
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=112a

  redis:
    image: "redis-noteflow"
    ports:
      - 6379:6379

volumes:
  data:
