openapi: 3.0.0
info:
  title: 軟體開發方法-第五組 noteflow
  description: 詳情請查閱 [github](https://github.com/vnaticzhock/noteflow-backend)
  version: 0.1
servers:
  - url: http://localhost/
    description: main server

paths:
  /:
    get:
      summary: 首頁
      description: 首頁
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /login:
    get:
      summary: 登入
      description: 登入
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: json
                items: 
                  type: string
  /login:
    post:
      summary: 登入
      description: 登入
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: json
                items: 
                  type: string
  /logout:
    post:
      summary: 登出
      description: 登出
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: json
                items: 
                  type: string